### ISSUE TITLE
unable to run tests sublime text 2

### ISSUE THREAD

**Issue by 0x4E0x650x6F** [stuartherbert/sublime-phpunit#47]
when i run tests this this is what shows in the console.

Traceback (most recent call last):
  File "./sublime_plugin.py", line 362, in run_
  File "./phpunit.py", line 769, in run
  File "./phpunit.py", line 276, in run
  File "./phpunit.py", line 234, in start_async
  File "./phpunit.py", line 101, in **init**
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/subprocess.py", line 623, in **init**
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/subprocess.py", line 1141, in _execute_child
    raise child_exception

**Comment by stuartherbert** [comment]
I'm not sure what is causing this. It could be that ST2 can't find 'phpunit' in your PATH.

I've just pushed a new feature, where this plugin will look in 'vendor/bin' for PHPUnit first. Can you let me know if that solves your problem?
